In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/pgshandino/Jobs-in-Nigeria/main/data/Jobs%20NG.csv"
df = pd.read_csv(url)
df.to_csv("data/raw/Jobs NG.csv", index=False)

In [2]:
df.shape

(3264, 13)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3264 entries, 0 to 3263
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             3264 non-null   str
 1   job_url          3264 non-null   str
 2   hiring_firm      3264 non-null   str
 3   hiring_firm_url  2600 non-null   str
 4   job_function     3264 non-null   str
 5   title            3264 non-null   str
 6   date_posted      3264 non-null   str
 7   Location         3264 non-null   str
 8   Job type         3264 non-null   str
 9   Industry         2820 non-null   str
 10  Salary           3264 non-null   str
 11  details          3264 non-null   str
 12  info             3264 non-null   str
dtypes: str(13)
memory usage: 331.6 KB

In [4]:
df.isna().sum()

name                 0
job_url              0
hiring_firm          0
hiring_firm_url    664
job_function         0
title                0
date_posted          0
Location             0
Job type             0
Industry           444
Salary               0
details              0
info                 0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(459)

In [6]:
df.head()

,name,job_url,hiring_firm,hiring_firm_url,job_function,title,date_posted,Location,Job type,Industry,Salary,details,info
0,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
1,3D Manager,https://www.jobberman.com/listings/3d-manager-...,Quorum West Africa,https://www.jobberman.com/jobs?q=Quorum%20West...,Job Function\n: Creative & Design,3D Manager,1 week ago,Abuja,Full Time,"Entertainment, Events & Sport","NGN\n\n150,000 - 250,000","['Minimum Qualification\n:\nDegree', 'Experien...","['Using 3D modeling, texture, mapping, and oth..."
2,Advocacy and Communications officer,https://www.jobberman.com/listings/advocacy-an...,Jileson Hub Plus Limited,https://www.jobberman.com/jobs?q=Jileson%20Hub...,Job Function\n: Community & Social Services,Advocacy and Communications officer,2 weeks ago,Rest of Nigeria (Kano),Full Time,Construction,"NGN\n\n150,000 - 250,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Identifying advocacy opportunities and prior...
3,Driver,https://www.jobberman.com/listings/driver-evvx45,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Job Function\n: Driver & Transport Services,Driver,Today,Lagos,Full Time,"Retail, Fashion & FMCG","NGN\n\n75,000 - 150,000","['Minimum Qualification\n:\nVocational', 'Expe...","['Collect goods from a shop, warehouse, or col..."
4,Store Manager,https://www.jobberman.com/listings/store-manag...,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Job Function\n: Management & Business Development,Store Manager,Today,Lagos,Full Time,"Retail, Fashion & FMCG","NGN\n\n75,000 - 150,000","['Minimum Qualification\n:\nOND', 'Experience ...","[""Develop business strategies to raise our cus..."

"Filled missing hiring_firm_url and Industry with 'Not Provided' — these are non-numeric categorical gaps, not something to calculate around."

In [7]:
df['hiring_firm_url'] = df['hiring_firm_url'].fillna('Not Provided')
df['Industry'] = df['Industry'].fillna('Not Provided')

In [8]:
# 1. Fully identical rows (every column matches)
print("Fully identical duplicate rows:", df.duplicated().sum())

# 2. Duplicates based on job_url only (the real identity of a posting)
print("Duplicate job_url rows:", df.duplicated(subset='job_url').sum())

# 3. Look at one duplicated job_url and see ALL its copies side by side
dupe_url = df[df.duplicated(subset='job_url', keep=False)]['job_url'].iloc[0]
df[df['job_url'] == dupe_url]

Fully identical duplicate rows: 459
Duplicate job_url rows: 459

,name,job_url,hiring_firm,hiring_firm_url,job_function,title,date_posted,Location,Job type,Industry,Salary,details,info
0,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
19,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
38,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
57,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
76,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
95,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
114,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
133,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
152,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
171,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
190,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
209,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
228,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
247,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
266,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
285,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
304,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
323,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
342,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
361,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
380,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
399,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
418,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
437,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
456,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
475,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
494,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
513,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
532,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
551,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
570,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
589,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
905,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...

Found 459 exact duplicate rows caused by a promoted/pinned listing reappearing on every scraped page (rows spaced ~19 apart, matching one page of results). Dropped with drop_duplicates() since every column matched — no information lost.

In [9]:
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"Removed {before - after} duplicate rows. New shape: {df.shape}")

df.duplicated().sum()   # should print 0

Removed 459 duplicate rows. New shape: (2805, 13)

np.int64(0)

In [10]:
df['job_function'].unique()

<StringArray>
[     'Job Function\n: Accounting, Auditing & Finance',
                   'Job Function\n: Creative & Design',
         'Job Function\n: Community & Social Services',
         'Job Function\n: Driver & Transport Services',
   'Job Function\n: Management & Business Development',
            'Job Function\n: Food Services & Catering',
            'Job Function\n: Engineering & Technology',
        'Job Function\n: Product & Project Management',
                     'Job Function\n: Software & Data',
                     'Job Function\n: Human Resources',
                               'Job Function\n: Sales',
          'Job Function\n: Marketing & Communications',
          'Job Function\n: Customer Service & Support',
       'Job Function\n: Research, Teaching & Training',
               'Job Function\n: Hospitality & Leisure',
                      'Job Function\n: Admin & Office',
             'Job Function\n: Building & Architecture',
                      'Job Function\n: Legal Services',
          'Job Function\n: Supply Chain & Procurement',
                     'Job Function\n: Health & Safety',
            'Job Function\n: Medical & Pharmaceutical',
         'Job Function\n: Quality Control & Assurance',
 'Job Function\n: Estate Agents & Property Management',
               'Job Function\n: Consulting & Strategy',
               'Job Function\n: Farming & Agriculture',
                   'Job Function\n: Trades & Services',
                         'Job Function\n: Unspecified']
Length: 27, dtype: str

job_function contained a repeated label prefix ("Job Function\n:") from the scrape, but the actual values were already a fixed, atomic set of 27 categories no multi-value splitting needed. Stripped the prefix only.

In [11]:
df['job_function'] = df['job_function'].str.replace('Job Function\n:', '', regex=False).str.strip()
df['job_function'].unique()

<StringArray>
[     'Accounting, Auditing & Finance',                   'Creative & Design',
         'Community & Social Services',         'Driver & Transport Services',
   'Management & Business Development',            'Food Services & Catering',
            'Engineering & Technology',        'Product & Project Management',
                     'Software & Data',                     'Human Resources',
                               'Sales',          'Marketing & Communications',
          'Customer Service & Support',       'Research, Teaching & Training',
               'Hospitality & Leisure',                      'Admin & Office',
             'Building & Architecture',                      'Legal Services',
          'Supply Chain & Procurement',                     'Health & Safety',
            'Medical & Pharmaceutical',         'Quality Control & Assurance',
 'Estate Agents & Property Management',               'Consulting & Strategy',
               'Farming & Agriculture',                   'Trades & Services',
                         'Unspecified']
Length: 27, dtype: str

In [12]:
df["Location"].unique()

<StringArray>
[ 'Port Harcourt & Rivers State',                         'Abuja',
        'Rest of Nigeria (Kano)',                         'Lagos',
       'Remote (Work From Home)',            'Ibadan & Oyo State',
         'Rest of Nigeria (Edo)',      'Rest of Nigeria (Kaduna)',
                         'Enugu',  'Rest of Nigeria (Nationwide)',
     'Rest of Nigeria (Anambra)',   'Rest of Nigeria (Nassarawa)',
               'Outside Nigeria',         'Abeokuta & Ogun State',
                           'Imo',       'Rest of Nigeria (Benue)',
      'Rest of Nigeria (Ebonyi)',     'Rest of Nigeria (Adamawa)',
        'Rest of Nigeria (Abia)',       'Rest of Nigeria (Kwara)',
       'Rest of Nigeria (Delta)',               'Rest of Nigeria',
        'Rest of Nigeria (Osun)',       'Rest of Nigeria (Niger)',
        'Rest of Nigeria (Ondo)',   'Rest of Nigeria (Akwa Ibom)',
     'Rest of Nigeria (Plateau)',       'Maiduguri & Borno State',
 'Rest of Nigeria (Cross River)',                   'Unspecified']
Length: 30, dtype: str

Location mixed city+state pairs, "Rest of Nigeria (State)" tags, and non-geographic categories (Remote, Nationwide, Outside Nigeria, Unspecified). Standardized everything to a single consistent value per row (mostly state names) since a stakeholder to clarify design intent wasn't available — chose the simplest structure for EDA usability.

In [13]:
import re

def clean_location(val):
    val = val.strip()
    if val.startswith('Rest of Nigeria ('):
        return val.split('(')[1].replace(')', '').strip()
    if val == 'Rest of Nigeria':
        return 'Unspecified'
    if '&' in val:
        return val.split('&')[1].replace('State', '').strip()
    return val

df['Location'] = df['Location'].apply(clean_location)
df['Location'].unique()

<StringArray>
[                 'Rivers',                   'Abuja',
                    'Kano',                   'Lagos',
 'Remote (Work From Home)',                     'Oyo',
                     'Edo',                  'Kaduna',
                   'Enugu',              'Nationwide',
                 'Anambra',               'Nassarawa',
         'Outside Nigeria',                    'Ogun',
                     'Imo',                   'Benue',
                  'Ebonyi',                 'Adamawa',
                    'Abia',                   'Kwara',
                   'Delta',             'Unspecified',
                    'Osun',                   'Niger',
                    'Ondo',               'Akwa Ibom',
                 'Plateau',                   'Borno',
             'Cross River']
Length: 29, dtype: str

In [14]:
df['Salary'].unique()

<StringArray>
[    'NGN\n\n600,000 - 900,000',     'NGN\n\n150,000 - 250,000',
      'NGN\n\n75,000 - 150,000',      'NGN\n\nLess than 75,000',
          'NGN\n\nConfidential',     'NGN\n\n250,000 - 400,000',
         'USD\n\n8000 - 10,000',     'NGN\n\n400,000 - 600,000',
 'NGN\n\n2,000,000 - 3,000,000',           'USD\n\n6000 - 8000',
           'USD\n\n1500 - 2500',       'NGN\n\nCommission Only',
 'NGN\n\n1,500,000 - 2,000,000',             'USD\n\n100 - 150',
   'NGN\n\n900,000 - 1,200,000',             'USD\n\n150 - 300',
         'USD\n\nLess than 100',           'USD\n\n1000 - 1500',
 'NGN\n\n4,000,000 - 5,000,000',             'USD\n\n300 - 500',
             'USD\n\n500 - 750',            'USD\n\n750 - 1000',
 'NGN\n\n1,200,000 - 1,500,000',       'USD\n\nCommission Only',
           'USD\n\n2500 - 4000',     'USD\n\nMore than 12,000+',
           'USD\n\n4000 - 6000',       'NGN\n\nAbove 5,000,000',
             'NGN\n\n150 - 300', 'NGN\n\n3,000,000 - 4,000,000']
Length: 30, dtype: str

In [15]:
df['Salary'].nunique()

30

In [16]:
df['Salary'].value_counts()

Salary
NGN\n\nConfidential             746
NGN\n\n75,000 - 150,000         728
NGN\n\nLess than 75,000         443
NGN\n\n150,000 - 250,000        417
NGN\n\n250,000 - 400,000        228
NGN\n\n400,000 - 600,000         84
NGN\n\n600,000 - 900,000         52
NGN\n\nCommission Only           20
NGN\n\n1,200,000 - 1,500,000     13
USD\n\n2500 - 4000               10
NGN\n\n900,000 - 1,200,000        9
NGN\n\n1,500,000 - 2,000,000      7
USD\n\n300 - 500                  6
USD\n\n500 - 750                  6
USD\n\n750 - 1000                 6
USD\n\nLess than 100              4
USD\n\n1000 - 1500                4
NGN\n\n2,000,000 - 3,000,000      3
USD\n\n6000 - 8000                3
USD\n\n1500 - 2500                3
USD\n\n100 - 150                  3
USD\n\n150 - 300                  2
USD\n\n8000 - 10,000              1
NGN\n\n4,000,000 - 5,000,000      1
USD\n\nCommission Only            1
USD\n\nMore than 12,000+          1
USD\n\n4000 - 6000                1
NGN\n\nAbove 5,000,000            1
NGN\n\n150 - 300                  1
NGN\n\n3,000,000 - 4,000,000      1
Name: count, dtype: int64

Salary combined currency, a text range, and special cases (Confidential, Commission Only, Less than/Above/More than) into one string. Split into currency, min_salary, max_salary (as floats, NaN where a bound is unknown), and salary_type to distinguish true ranges from non-numeric cases. Manually recoded one mislabeled row (NGN 150-300 → USD) that didn't match the NGN scale. Dropped the original Salary column after parsing.

In [17]:
df.loc[df['Salary'] == 'NGN\n\n150 - 300', 'Salary'] = 'USD\n\n150 - 300'

In [18]:
import re
import numpy as np

def parse_salary(val):
    currency, amount = val.split('\n\n')
    amount = amount.strip()
    
    if amount in ['Confidential', 'Commission Only']:
        return pd.Series([currency, np.nan, np.nan, amount])
    
    if amount.startswith('Less than'):
        num = float(re.sub(r'[^\d.]', '', amount))
        return pd.Series([currency, np.nan, num, 'Less than'])
    
    if amount.startswith('Above'):
        num = float(re.sub(r'[^\d.]', '', amount))
        return pd.Series([currency, num, np.nan, 'Above'])
    
    if amount.startswith('More than'):
        num = float(re.sub(r'[^\d.]', '', amount))
        return pd.Series([currency, num, np.nan, 'More than'])
    
    # standard range, e.g. "75,000 - 150,000"
    parts = amount.split('-')
    low = float(re.sub(r'[^\d.]', '', parts[0]))
    high = float(re.sub(r'[^\d.]', '', parts[1]))
    return pd.Series([currency, low, high, 'Range'])

df[['currency', 'min_salary', 'max_salary', 'salary_type']] = df['Salary'].apply(parse_salary)

In [19]:
df['salary_type'].value_counts()
df['currency'].value_counts()
df[['Salary', 'currency', 'min_salary', 'max_salary', 'salary_type']].sample(10)

                        Salary currency  min_salary  max_salary   salary_type
901   NGN\n\n150,000 - 250,000      NGN    150000.0    250000.0         Range
1854   NGN\n\n75,000 - 150,000      NGN     75000.0    150000.0         Range
1771   NGN\n\n75,000 - 150,000      NGN     75000.0    150000.0         Range
1523   NGN\n\nLess than 75,000      NGN         NaN     75000.0     Less than
1866       NGN\n\nConfidential      NGN         NaN         NaN  Confidential
701    NGN\n\n75,000 - 150,000      NGN     75000.0    150000.0         Range
1828  NGN\n\n150,000 - 250,000      NGN    150000.0    250000.0         Range
583    NGN\n\n75,000 - 150,000      NGN     75000.0    150000.0         Range
1663  NGN\n\n150,000 - 250,000      NGN    150000.0    250000.0         Range
1580   NGN\n\n75,000 - 150,000      NGN     75000.0    150000.0         Range

In [20]:
df[df['salary_type'].isin(['Less than', 'Above', 'More than', 'Commission Only'])][['Salary', 'currency', 'min_salary', 'max_salary', 'salary_type']].drop_duplicates()

,Salary,currency,min_salary,max_salary,salary_type
5,"NGN\n\nLess than 75,000",NGN,NaN,75000.0,Less than
122,NGN\n\nCommission Only,NGN,NaN,NaN,Commission Only
330,USD\n\nLess than 100,USD,NaN,100.0,Less than
1125,USD\n\nCommission Only,USD,NaN,NaN,Commission Only
1309,"USD\n\nMore than 12,000+",USD,12000.0,NaN,More than
1486,"NGN\n\nAbove 5,000,000",NGN,5000000.0,NaN,Above

In [21]:
df = df.drop(columns=['Salary'])
df.columns

Index(['name', 'job_url', 'hiring_firm', 'hiring_firm_url', 'job_function',
       'title', 'date_posted', 'Location', 'Job type', 'Industry', 'details',
       'info', 'currency', 'min_salary', 'max_salary', 'salary_type'],
      dtype='str')

details stored qualification, experience level, and experience length as a stringified list with inconsistent completeness (2,200 rows full, 599 empty, 6 partial). Extracted each into its own column (min_qualification, experience_level, experience_length), filling missing pieces with "Not Provided" for consistency with other categorical gaps in the dataset. Dropped the original column after parsing.

In [22]:
df['details'].iloc[0]
df['details'].iloc[1]
df['details'].iloc[2]

"['Minimum Qualification\\n:\\nDegree', 'Experience Level\\n:\\nMid level', 'Experience Length\\n:\\n3 years']"

In [23]:
# How many items are in each row's list?
df['details'].str.count(r"',\s*'").add(1).value_counts()

details
3    2200
1     605
Name: count, dtype: int64

In [24]:
import re

def get_labels(s):
    return re.findall(r"'([^\\']+?)\\n:", s)

df['details'].apply(get_labels).apply(tuple).value_counts()

details
(Minimum Qualification, Experience Level, Experience Length)    2200
()                                                               599
(Minimum Qualification,)                                           6
Name: count, dtype: int64

In [25]:
print(df.loc[599, 'details'])

['Minimum Qualification\n:\nDegree', 'Experience Level\n:\nMid level', 'Experience Length\n:\n2 years']

In [28]:
# Find the actual rows where our check found nothing
mask_empty = df['details'].apply(lambda s: len(re.findall(r"'([^\\']+?)\\n:", s)) == 0)

# Show me the row numbers, and print a few of them
weird_rows = df[mask_empty].index.tolist()
print(weird_rows[:5])

[2612, 2613, 2614, 2615, 2616]

In [29]:
print(df.loc[weird_rows[0], 'details'])

[]

In [30]:
import re

def parse_details(s):
    quals = re.findall(r"Minimum Qualification\\n:\\n([^']+)", s)
    levels = re.findall(r"Experience Level\\n:\\n([^']+)", s)
    lengths = re.findall(r"Experience Length\\n:\\n([^']+)", s)
    
    qual = quals[0] if quals else 'Not Provided'
    level = levels[0] if levels else 'Not Provided'
    length = lengths[0] if lengths else 'Not Provided'
    
    return pd.Series([qual, level, length])

df[['min_qualification', 'experience_level', 'experience_length']] = df['details'].apply(parse_details)

In [31]:
# A normal full row
print(df.loc[0, ['min_qualification', 'experience_level', 'experience_length']])

# One of the empty ones
print(df.loc[2612, ['min_qualification', 'experience_level', 'experience_length']])

# One of the 6 partial ones - let's grab one
partial_idx = df[df['details'].apply(lambda s: re.findall(r"'([^\\']+?)\\n:", s) == ['Minimum Qualification'])].index[0]
print(df.loc[partial_idx, ['min_qualification', 'experience_level', 'experience_length']])

min_qualification             Degree
experience_level     Executive level
experience_length           10 years
Name: 0, dtype: str
min_qualification    Not Provided
experience_level     Not Provided
experience_length    Not Provided
Name: 2612, dtype: str
min_qualification             HND
experience_level     Not Provided
experience_length    Not Provided
Name: 3211, dtype: str

In [32]:
df = df.drop(columns=['details'])
df.columns

Index(['name', 'job_url', 'hiring_firm', 'hiring_firm_url', 'job_function',
       'title', 'date_posted', 'Location', 'Job type', 'Industry', 'info',
       'currency', 'min_salary', 'max_salary', 'salary_type',
       'min_qualification', 'experience_level', 'experience_length'],
      dtype='str')

date_posted used relative text ("2 weeks ago", "Today") with no confirmed scrape date available from the source repo, so an exact calendar date couldn't be reconstructed. Converted to days_ago (integer), treating weeks as 7 days and months as 30 days (approximate). Kept as a pure numeric column — unlike other cleaned columns, no "Not Provided" fallback was used here since every value in the source column matched a known pattern, and mixing text into a numeric column would break downstream math/sorting.

In [33]:
df['date_posted'].unique()

<StringArray>
[ '2 weeks ago',   '1 week ago',        'Today',   '3 days ago',
   '4 days ago',   '5 days ago',   '6 days ago',  '1 month ago',
  '3 weeks ago',  '4 weeks ago', '2 months ago',    'Yesterday',
   '2 days ago']
Length: 13, dtype: str

In [34]:
def parse_days_ago(val):
    val = val.strip()
    if val == 'Today':
        return 0
    if val == 'Yesterday':
        return 1
    match = re.match(r'(\d+)\s+(day|week|month)s?\s+ago', val)
    num, unit = int(match.group(1)), match.group(2)
    if unit == 'day':
        return num
    if unit == 'week':
        return num * 7
    return num * 30  # month

df['days_ago'] = df['date_posted'].apply(parse_days_ago)
df[['date_posted', 'days_ago']].drop_duplicates().sort_values('days_ago')

       date_posted  days_ago
3            Today         0
2613     Yesterday         1
2618    2 days ago         2
60      3 days ago         3
130     4 days ago         4
177     5 days ago         5
239     6 days ago         6
1       1 week ago         7
0      2 weeks ago        14
610    3 weeks ago        21
1288   4 weeks ago        28
608    1 month ago        30
2494  2 months ago        60

In [35]:
df = df.drop(columns=['date_posted'])
df.columns

Index(['name', 'job_url', 'hiring_firm', 'hiring_firm_url', 'job_function',
       'title', 'Location', 'Job type', 'Industry', 'info', 'currency',
       'min_salary', 'max_salary', 'salary_type', 'min_qualification',
       'experience_level', 'experience_length', 'days_ago'],
      dtype='str')

In [36]:
df['info'].iloc[0]
df['info'].iloc[1]
df['info'].iloc[2]

"['Identifying advocacy opportunities and priorities, and executing strategy.Designing and implementing human rights programsMaintain existing partnerships and grow the organization’s network of strategic partnersMaintain strong relationships with internal and external partnersPreparing proposals, reports, briefings, and other such publicationsPrepare final project reports, providing feedback to donors while critically assessing every project for growth and sustainabilitySupport and build on the organization’s monitoring and evaluation strategy and frameworkContent development for the organization’s website, annual report, social media, events, email newsletters, and other materialsKeep a finger on the pulse of relevant literature, articles, events, conferences, and trending news related to WISE’s projects and industry spaceSupport organization-wide activities, events, and campaigns actively and as neededPerforming any other duties that may be assigned by the supervisor.Develop a good communications plan and create a series of communications and advocacy toolsEngage with local partners to build and cultivate strategic partnerships to leverage advocacy opportunities with government leadership, Ministries, other implementing partnersSupport the design of advocacy strategies and country engagement plans in collaboration with the project team.', 'A degree in Mass Communication, English and literature studies, or Art and Humanity studies.At least (3) three years of relevant work experience in the NGO space.Excellent Oral and Written Communication Skills.Fluency in English; fluency in Hausa is an advantageAbility to multitask and work within deadlinesDiscretion and ability to handle confidential issues.Ability to work collaboratively and respectfully with people from varied backgrounds and cultures at all levelsConfidence and enthusiasm when communicating with both external partners and the internal project teams in formal and informal presentationsProficient in the use of Microsoft applications, including Excel, Word, and PowerPointStrong team playerStrong problem-solving, analytical, operational, and coordinating abilitiesExcellent planning, organizational, time management, and people skills.Passion for human rights, specifically, LGBTQ rights and EquityPersonal qualities of integrity, sense of humor, humility, creativity, and ability to take initiative.']"

info contained long free-text paragraphs (job description and requirements), not structured for EDA/SQL/Power BI analysis. Dropped, since this project focuses on quantitative and categorical insights rather than text analysis.

In [37]:
# How many items are in each row's info list? (should mostly be 2: description + requirements)
df['info'].str.count(r"',\s*'").add(1).value_counts()

info
1     1282
2     1005
3      244
4       80
5       42
6       40
7       36
8       33
9       21
10      11
11       9
12       1
13       1
Name: count, dtype: int64

In [38]:
df = df.drop(columns=['info'])
df.columns

Index(['name', 'job_url', 'hiring_firm', 'hiring_firm_url', 'job_function',
       'title', 'Location', 'Job type', 'Industry', 'currency', 'min_salary',
       'max_salary', 'salary_type', 'min_qualification', 'experience_level',
       'experience_length', 'days_ago'],
      dtype='str')