In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/pgshandino/Jobs-in-Nigeria/main/data/Jobs%20NG.csv"
df = pd.read_csv(url)
df.to_csv("data/raw/Jobs NG.csv", index=False)

In [3]:
df.shape

(3264, 13)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3264 entries, 0 to 3263
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             3264 non-null   str
 1   job_url          3264 non-null   str
 2   hiring_firm      3264 non-null   str
 3   hiring_firm_url  2600 non-null   str
 4   job_function     3264 non-null   str
 5   title            3264 non-null   str
 6   date_posted      3264 non-null   str
 7   Location         3264 non-null   str
 8   Job type         3264 non-null   str
 9   Industry         2820 non-null   str
 10  Salary           3264 non-null   str
 11  details          3264 non-null   str
 12  info             3264 non-null   str
dtypes: str(13)
memory usage: 331.6 KB

In [7]:
df.isna().sum()

name                 0
job_url              0
hiring_firm          0
hiring_firm_url    664
job_function         0
title                0
date_posted          0
Location             0
Job type             0
Industry           444
Salary               0
details              0
info                 0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(459)

In [9]:
df.head()

,name,job_url,hiring_firm,hiring_firm_url,job_function,title,date_posted,Location,Job type,Industry,Salary,details,info
0,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
1,3D Manager,https://www.jobberman.com/listings/3d-manager-...,Quorum West Africa,https://www.jobberman.com/jobs?q=Quorum%20West...,Job Function\n: Creative & Design,3D Manager,1 week ago,Abuja,Full Time,"Entertainment, Events & Sport","NGN\n\n150,000 - 250,000","['Minimum Qualification\n:\nDegree', 'Experien...","['Using 3D modeling, texture, mapping, and oth..."
2,Advocacy and Communications officer,https://www.jobberman.com/listings/advocacy-an...,Jileson Hub Plus Limited,https://www.jobberman.com/jobs?q=Jileson%20Hub...,Job Function\n: Community & Social Services,Advocacy and Communications officer,2 weeks ago,Rest of Nigeria (Kano),Full Time,Construction,"NGN\n\n150,000 - 250,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Identifying advocacy opportunities and prior...
3,Driver,https://www.jobberman.com/listings/driver-evvx45,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Job Function\n: Driver & Transport Services,Driver,Today,Lagos,Full Time,"Retail, Fashion & FMCG","NGN\n\n75,000 - 150,000","['Minimum Qualification\n:\nVocational', 'Expe...","['Collect goods from a shop, warehouse, or col..."
4,Store Manager,https://www.jobberman.com/listings/store-manag...,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Job Function\n: Management & Business Development,Store Manager,Today,Lagos,Full Time,"Retail, Fashion & FMCG","NGN\n\n75,000 - 150,000","['Minimum Qualification\n:\nOND', 'Experience ...","[""Develop business strategies to raise our cus..."

"Filled missing hiring_firm_url and Industry with 'Not Provided' — these are non-numeric categorical gaps, not something to calculate around."

In [14]:
df['hiring_firm_url'] = df['hiring_firm_url'].fillna('Not Provided')
df['Industry'] = df['Industry'].fillna('Not Provided')

In [12]:
# 1. Fully identical rows (every column matches)
print("Fully identical duplicate rows:", df.duplicated().sum())

# 2. Duplicates based on job_url only (the real identity of a posting)
print("Duplicate job_url rows:", df.duplicated(subset='job_url').sum())

# 3. Look at one duplicated job_url and see ALL its copies side by side
dupe_url = df[df.duplicated(subset='job_url', keep=False)]['job_url'].iloc[0]
df[df['job_url'] == dupe_url]

Fully identical duplicate rows: 459
Duplicate job_url rows: 459

,name,job_url,hiring_firm,hiring_firm_url,job_function,title,date_posted,Location,Job type,Industry,Salary,details,info
0,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
19,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
38,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
57,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
76,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
95,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
114,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
133,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
152,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
171,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
190,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
209,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
228,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
247,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
266,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
285,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
304,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
323,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
342,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
361,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
380,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
399,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
418,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
437,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
456,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
475,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
494,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
513,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
532,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
551,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
570,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
589,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...
905,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Job Function\n: Accounting, Auditing & Finance",Chief Financial Officer (CFO),2 weeks ago,Port Harcourt & Rivers State,Full Time,"Banking, Finance & Insurance","NGN\n\n600,000 - 900,000","['Minimum Qualification\n:\nDegree', 'Experien...",['Develop and implement financial strategies t...

Found 459 exact duplicate rows caused by a promoted/pinned listing reappearing on every scraped page (rows spaced ~19 apart, matching one page of results). Dropped with drop_duplicates() since every column matched — no information lost.

In [13]:
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"Removed {before - after} duplicate rows. New shape: {df.shape}")

df.duplicated().sum()   # should print 0

Removed 459 duplicate rows. New shape: (2805, 13)

np.int64(0)