In [24]:
import pandas as pd 
df=pd.read_csv('data/clean/jobs_ng_cleaned.csv')

In [25]:
df.head()

,name,job_url,hiring_firm,hiring_firm_url,job_function,title,Location,Job type,Industry,currency,min_salary,max_salary,salary_type,min_qualification,experience_level,experience_length,days_ago
0,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Accounting, Auditing & Finance",Chief Financial Officer (CFO),Rivers,Full Time,"Banking, Finance & Insurance",NGN,600000.0,900000.0,Range,Degree,Executive level,10 years,14
1,3D Manager,https://www.jobberman.com/listings/3d-manager-...,Quorum West Africa,https://www.jobberman.com/jobs?q=Quorum%20West...,Creative & Design,3D Manager,Abuja,Full Time,"Entertainment, Events & Sport",NGN,150000.0,250000.0,Range,Degree,Mid level,4 years,7
2,Advocacy and Communications officer,https://www.jobberman.com/listings/advocacy-an...,Jileson Hub Plus Limited,https://www.jobberman.com/jobs?q=Jileson%20Hub...,Community & Social Services,Advocacy and Communications officer,Kano,Full Time,Construction,NGN,150000.0,250000.0,Range,Degree,Mid level,3 years,14
3,Driver,https://www.jobberman.com/listings/driver-evvx45,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Driver & Transport Services,Driver,Lagos,Full Time,"Retail, Fashion & FMCG",NGN,75000.0,150000.0,Range,Vocational,Entry level,1 year,0
4,Store Manager,https://www.jobberman.com/listings/store-manag...,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Management & Business Development,Store Manager,Lagos,Full Time,"Retail, Fashion & FMCG",NGN,75000.0,150000.0,Range,OND,Mid level,3 years,0

## Most In-Demand Job Functions

Sales (315 postings) and Marketing & Communications (308) are the two most 
common job functions in this dataset, ahead of Engineering & Technology (232) 
and Software & Data (173).

A follow-up check showed Sales jobs are spread across 19 of 22 industries, 
rather than concentrated in one sector. This explains why Sales tops the list: 
it is a role nearly every type of business needs, not a role tied to one 
specific industry.

In [26]:
df['job_function'].value_counts()

job_function
Sales                                  315
Marketing & Communications             308
Management & Business Development      257
Accounting, Auditing & Finance         234
Engineering & Technology               232
Software & Data                        173
Admin & Office                         168
Research, Teaching & Training          119
Creative & Design                      101
Customer Service & Support             100
Driver & Transport Services             97
Human Resources                         93
Hospitality & Leisure                   89
Product & Project Management            61
Medical & Pharmaceutical                61
Food Services & Catering                59
Supply Chain & Procurement              58
Legal Services                          57
Building & Architecture                 44
Trades & Services                       36
Health & Safety                         34
Estate Agents & Property Management     26
Quality Control & Assurance             24
Community & Social Services             22
Farming & Agriculture                   19
Consulting & Strategy                   16
Unspecified                              2
Name: count, dtype: int64

## Most In-Demand Industries

Excluding "Not Provided" (jobs with no industry listed), IT & Telecoms leads 
with 312 postings, followed by Hospitality & Hotel (267) and Banking, Finance 
& Insurance (255).

In [27]:
df['Industry'].value_counts()

Industry
Not Provided                           438
IT & Telecoms                          312
Hospitality & Hotel                    267
Banking, Finance & Insurance           255
Retail, Fashion & FMCG                 186
Real Estate                            157
Education                              152
Advertising, Media & Communications    134
Construction                           128
Healthcare                             116
Energy & Utilities                     115
Manufacturing & Warehousing            108
Entertainment, Events & Sport           68
Shipping & Logistics                    67
Agriculture, Fishing & Forestry         61
Recruitment                             59
Tourism & Travel                        49
NGO, NPO & Charity                      40
Law & Compliance                        36
Mining, Energy & Metals                 25
Automotive & Aviation                   22
Enforcement & Security                   9
Government                               1
Name: count, dtype: int64

In [28]:
df[df['job_function'] == 'Sales']['Industry'].value_counts()

Industry
Retail, Fashion & FMCG                 47
Real Estate                            43
Banking, Finance & Insurance           36
IT & Telecoms                          31
Not Provided                           27
Manufacturing & Warehousing            23
Energy & Utilities                     18
Construction                           12
Hospitality & Hotel                    11
Education                              11
Advertising, Media & Communications    11
Shipping & Logistics                   10
Recruitment                             9
Healthcare                              8
Tourism & Travel                        7
Entertainment, Events & Sport           4
Agriculture, Fishing & Forestry         4
Automotive & Aviation                   2
NGO, NPO & Charity                      1
Name: count, dtype: int64

In [29]:
df['currency'].value_counts()

currency
NGN    2753
USD      52
Name: count, dtype: int64

In [30]:
df['salary_type'].value_counts()

salary_type
Range              1589
Confidential        746
Less than           447
Commission Only      21
More than             1
Above                 1
Name: count, dtype: int64

## Average Pay by Job Function

Engineering & Technology has the highest average pay (₦396,310), followed by 
Product & Project Management (₦377,451) and Management & Business Development 
(₦365,728).

Notably, Sales — the most in-demand job function — ranks only mid-table in pay 
(₦195,343), roughly half of Engineering & Technology. This shows that demand 
(number of postings) and pay do not always move together.

Averages are based only on postings in Naira with a full salary range stated. 
Categories with very few postings (e.g. Trades & Services, 3 jobs) should be 
treated as rough estimates, not reliable figures.

In [31]:
ngn_range = df[(df['currency'] == 'NGN') & (df['salary_type'] == 'Range')].copy()
ngn_range['avg_salary'] = (ngn_range['min_salary'] + ngn_range['max_salary']) / 2

ngn_range.groupby('job_function')['avg_salary'].mean().sort_values(ascending=False)

job_function
Engineering & Technology               396309.523810
Product & Project Management           377450.980392
Management & Business Development      365728.476821
Quality Control & Assurance            363281.250000
Building & Architecture                335344.827586
Software & Data                        298875.000000
Health & Safety                        297916.666667
Farming & Agriculture                  277083.333333
Consulting & Strategy                  266071.428571
Accounting, Auditing & Finance         240441.176471
Medical & Pharmaceutical               235227.272727
Human Resources                        227976.190476
Marketing & Communications             214002.732240
Estate Agents & Property Management    212500.000000
Legal Services                         195416.666667
Sales                                  195343.137255
Admin & Office                         171947.674419
Research, Teaching & Training          165625.000000
Supply Chain & Procurement             162037.037037
Creative & Design                      161914.062500
Food Services & Catering               161206.896552
Hospitality & Leisure                  160714.285714
Customer Service & Support             156458.333333
Community & Social Services            156250.000000
Trades & Services                      141666.666667
Driver & Transport Services            112500.000000
Name: avg_salary, dtype: float64

In [32]:
ngn_range.groupby('job_function')['avg_salary'].count().sort_values(ascending=False)

job_function
Sales                                  204
Marketing & Communications             183
Management & Business Development      151
Accounting, Auditing & Finance         136
Engineering & Technology               105
Software & Data                        100
Admin & Office                          86
Research, Teaching & Training           68
Creative & Design                       64
Customer Service & Support              60
Product & Project Management            51
Hospitality & Leisure                   42
Human Resources                         42
Legal Services                          30
Driver & Transport Services             30
Food Services & Catering                29
Building & Architecture                 29
Supply Chain & Procurement              27
Medical & Pharmaceutical                22
Estate Agents & Property Management     19
Quality Control & Assurance             16
Consulting & Strategy                   14
Farming & Agriculture                   12
Health & Safety                         12
Community & Social Services              8
Trades & Services                        3
Name: avg_salary, dtype: int64

## Average Pay by Industry

Energy & Utilities has the highest average pay (₦449,537, based on 81 
postings), followed by IT & Telecoms (₦326,312) and Banking, Finance & 
Insurance (₦299,483).

Government and Enforcement & Security show the lowest postings in the clean 
salary data (1 and 3 jobs respectively) and their averages are not reliable.

In [33]:
ngn_range.groupby('Industry')['avg_salary'].mean().sort_values(ascending=False)

Industry
Energy & Utilities                     449537.037037
IT & Telecoms                          326312.154696
Banking, Finance & Insurance           299482.758621
Manufacturing & Warehousing            255448.717949
Construction                           241801.075269
Healthcare                             241071.428571
Shipping & Logistics                   230555.555556
Automotive & Aviation                  227631.578947
Retail, Fashion & FMCG                 222129.629630
Real Estate                            221008.403361
Agriculture, Fishing & Forestry        220426.829268
Tourism & Travel                       216463.414634
Mining, Energy & Metals                215277.777778
Enforcement & Security                 212500.000000
Recruitment                            202925.531915
Education                              189460.784314
Entertainment, Events & Sport          185106.382979
Law & Compliance                       178846.153846
Advertising, Media & Communications    173638.613861
NGO, NPO & Charity                     173148.148148
Hospitality & Hotel                    154573.170732
Government                             112500.000000
Name: avg_salary, dtype: float64

In [34]:
ngn_range.groupby('Industry')['avg_salary'].count().sort_values(ascending=False)

Industry
IT & Telecoms                          181
Banking, Finance & Insurance           145
Retail, Fashion & FMCG                 135
Hospitality & Hotel                    123
Real Estate                            119
Education                              102
Advertising, Media & Communications    101
Construction                            93
Energy & Utilities                      81
Manufacturing & Warehousing             78
Healthcare                              70
Entertainment, Events & Sport           47
Recruitment                             47
Shipping & Logistics                    45
Tourism & Travel                        41
Agriculture, Fishing & Forestry         41
NGO, NPO & Charity                      27
Law & Compliance                        26
Automotive & Aviation                   19
Mining, Energy & Metals                 18
Enforcement & Security                   3
Government                               1
Name: avg_salary, dtype: int64

In [35]:
df['experience_level'].value_counts()

experience_level
Mid level                940
Entry level              744
Not Provided             605
Senior level             332
Internship & Graduate     80
No Experience             54
Executive level           50
Name: count, dtype: int64

In [36]:

df['experience_length'].value_counts()

experience_length
Not Provided                      605
2 years                           581
1 year                            480
3 years                           466
5 years                           234
No Experience/Less than 1 year    175
4 years                           118
10 years                           48
7 years                            40
8 years                            29
6 years                            16
15 years                           10
12 years                            2
16 years                            1
Name: count, dtype: int64

## Average Pay by Experience Level

Pay increases steadily and predictably with experience level:

- Internship & Graduate: ₦116,667
- No Experience: ₦119,792
- Entry level: ₦139,904
- Mid level: ₦208,355
- Senior level: ₦462,142
- Executive level: ₦711,328

Executive-level roles pay roughly 6 times more than Internship/Graduate roles, 
making experience level the strongest and most consistent salary driver found 
in this analysis.

In [37]:
ngn_range.groupby('experience_level')['avg_salary'].agg(['mean', 'count']).sort_values('mean', ascending=False)

                                mean  count
experience_level
Executive level        711328.125000     32
Senior level           462141.577061    279
Mid level              208355.350066    757
Entry level            139903.846154    442
No Experience          119791.666667     12
Internship & Graduate  116666.666667     21

## Job Postings and Pay by Location

Lagos dominates job postings, accounting for 1,518 of 2,805 jobs (about 54%) — 
more than every other location combined. Abuja is a distant second (329), 
followed by Rivers State (116).

However, Lagos is not the highest-paying location. Despite having the most 
postings by far, Lagos ranks 10th in average pay (₦234,262). Rivers State has 
the highest reliable average pay (₦424,209, based on 79 postings), likely 
driven by its oil and gas industry presence — consistent with Energy & 
Utilities also being the top-paying industry overall.

This suggests Lagos offers the most job opportunities by volume, but not 
necessarily the best-paying ones.

In [38]:
df["Location"].value_counts()

Location
Lagos                      1518
Unspecified                 371
Abuja                       329
Rivers                      116
Remote (Work From Home)     106
Oyo                          46
Edo                          43
Abia                         42
Ogun                         37
Delta                        28
Imo                          25
Anambra                      22
Nationwide                   16
Kano                         14
Nassarawa                    12
Enugu                        11
Kwara                        11
Osun                         11
Ondo                          9
Outside Nigeria               8
Ebonyi                        7
Kaduna                        6
Cross River                   6
Benue                         5
Akwa Ibom                     2
Adamawa                       1
Niger                         1
Plateau                       1
Borno                         1
Name: count, dtype: int64

In [39]:
ngn_range.groupby('Location')['avg_salary'].agg(['mean', 'count']).sort_values('mean', ascending=False)

                                  mean  count
Location
Nationwide               470312.500000      8
Kwara                    435416.666667      6
Rivers                   424208.860759     79
Remote (Work From Home)  343981.481481     54
Cross River              320833.333333      6
Ondo                     306250.000000      4
Delta                    272368.421053     19
Enugu                    271428.571429      7
Imo                      256250.000000     14
Lagos                    234262.125903    969
Abuja                    223878.205128    234
Unspecified              200000.000000      1
Edo                      193359.375000     32
Kaduna                   183333.333333      3
Kano                     172916.666667     12
Oyo                      166304.347826     23
Nassarawa                165277.777778      9
Abia                     163235.294118     17
Ogun                     146022.727273     22
Anambra                  140178.571429     14
Osun                     130000.000000      5
Benue                    112500.000000      4
Adamawa                  112500.000000      1

## Average Pay by Minimum Qualification

Pay rises with required qualification level:

- High School (S.S.C.E): ₦120,833
- OND: ₦133,079
- Diploma: ₦138,133
- HND: ₦179,867
- Degree: ₦290,995
- MBA / MSc: ₦536,000

Degree is the most common requirement (887 clean postings) and pays notably 
more than HND or OND. Postgraduate qualifications (MBA/MSc, MPhil/PhD, MBBS) 
have very few postings in this dataset and should be read as indicative only, 
not conclusive.

In [40]:
df['min_qualification'].value_counts()

min_qualification
Degree                   1102
Not Provided              599
HND                       459
High School (S.S.C.E)     234
OND                       148
Diploma                   139
Others                     65
MBA / MSc                  29
N.C.E                      14
Vocational                 12
MBBS                        3
MPhil / PhD                 1
Name: count, dtype: int64

In [41]:
ngn_range.groupby('min_qualification')['avg_salary'].agg(['mean', 'count']).sort_values('mean', ascending=False)

                                mean  count
min_qualification
MBA / MSc              536000.000000     25
MPhil / PhD            500000.000000      1
MBBS                   325000.000000      3
Degree                 290994.926719    887
Others                 189224.137931     29
N.C.E                  185000.000000     10
HND                    179866.946779    357
Vocational             167857.142857      7
Diploma                138132.911392     79
OND                    133079.268293     82
High School (S.S.C.E)  120833.333333     63

In [42]:
%pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\Users\chukw\anaconda3\envs\pyhton_course\Lib\site-packages (2.1.4)
Requirement already satisfied: psycopg2-binary in c:\Users\chukw\anaconda3\envs\pyhton_course\Lib\site-packages (2.9.13)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\chukw\anaconda3\envs\pyhton_course\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
%pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\Users\chukw\anaconda3\envs\pyhton_course\Lib\site-packages (2.9.13)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import sys
print(sys.executable)

c:\Users\chukw\anaconda3\envs\pyhton_course\python.exe

In [ ]:
import sys
!{sys.executable} -m pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\Users\chukw\anaconda3\envs\pyhton_course\Lib\site-packages (2.9.13)

In [46]:
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://postgres:123@localhost:5432/nigerian_jobs')

df.to_sql('job_postings', engine, if_exists='replace', index=False)

805

In [48]:
pd.read_sql('SELECT * FROM job_postings LIMIT 5;', engine)

,name,job_url,hiring_firm,hiring_firm_url,job_function,title,Location,Job type,Industry,currency,min_salary,max_salary,salary_type,min_qualification,experience_level,experience_length,days_ago
0,Chief Financial Officer (CFO),https://www.jobberman.com/listings/chief-finan...,Gelose Marine Nigeria Limited,https://www.jobberman.com/jobs?q=Gelose%20Mari...,"Accounting, Auditing & Finance",Chief Financial Officer (CFO),Rivers,Full Time,"Banking, Finance & Insurance",NGN,600000.0,900000.0,Range,Degree,Executive level,10 years,14
1,3D Manager,https://www.jobberman.com/listings/3d-manager-...,Quorum West Africa,https://www.jobberman.com/jobs?q=Quorum%20West...,Creative & Design,3D Manager,Abuja,Full Time,"Entertainment, Events & Sport",NGN,150000.0,250000.0,Range,Degree,Mid level,4 years,7
2,Advocacy and Communications officer,https://www.jobberman.com/listings/advocacy-an...,Jileson Hub Plus Limited,https://www.jobberman.com/jobs?q=Jileson%20Hub...,Community & Social Services,Advocacy and Communications officer,Kano,Full Time,Construction,NGN,150000.0,250000.0,Range,Degree,Mid level,3 years,14
3,Driver,https://www.jobberman.com/listings/driver-evvx45,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Driver & Transport Services,Driver,Lagos,Full Time,"Retail, Fashion & FMCG",NGN,75000.0,150000.0,Range,Vocational,Entry level,1 year,0
4,Store Manager,https://www.jobberman.com/listings/store-manag...,Espago Luxe Enterprises,https://www.jobberman.com/jobs?q=Espago%20Luxe...,Management & Business Development,Store Manager,Lagos,Full Time,"Retail, Fashion & FMCG",NGN,75000.0,150000.0,Range,OND,Mid level,3 years,0